//@author Yağmur Doğan

import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmAdd extends javax.swing.JFrame {

    Connection connection = null;
    DbHelper dbHelper = new DbHelper();
    DefaultTableModel model;
    Statement statement = null;
    ResultSet resultSet;
    ArrayList<Client> clients = null; //For data tables

    public frmAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lblAddingData1 = new javax.swing.JLabel();
        btnAddClient = new javax.swing.JButton();
        btnAddHomePage = new javax.swing.JButton();
        btnAddReservation = new javax.swing.JButton();
        btnAddPayment = new javax.swing.JButton();
        btnAddEmployee = new javax.swing.JButton();
        txtClientID = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        txtClientAddress = new javax.swing.JTextField();
        txtClientFaculty = new javax.swing.JTextField();
        txtClientEDate = new javax.swing.JTextField();
        txtClientPID = new javax.swing.JTextField();
        txtClientRID = new javax.swing.JTextField();
        txtClientCID = new javax.swing.JTextField();
        txtMealType = new javax.swing.JTextField();
        txtMealPrice = new javax.swing.JTextField();
        txtMealCID = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        txtEmployeeName = new javax.swing.JTextField();
        txtEmployeeAddress = new javax.swing.JTextField();
        txtEmployeeStartDate = new javax.swing.JTextField();
        txtEmployeeCID = new javax.swing.JTextField();
        txtPaymentDate = new javax.swing.JTextField();
        txtPaymentMethod = new javax.swing.JTextField();
        txtPaymentID = new javax.swing.JTextField();
        txtPaymentMealType = new javax.swing.JTextField();
        txtReservationDate = new javax.swing.JTextField();
        txtReservationMethod = new javax.swing.JTextField();
        txtReservationID = new javax.swing.JTextField();
        txtReservationMealType = new javax.swing.JTextField();
        btnAddMeal = new javax.swing.JButton();
        btnAddUpdate = new javax.swing.JButton();
        btnAddTable = new javax.swing.JButton();
        btnAddDelete = new javax.swing.JButton();
        cmbEmployeeGender = new javax.swing.JComboBox<>();
        cmbClientGender = new javax.swing.JComboBox<>();
        cmbClientType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAddingData1.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        lblAddingData1.setForeground(new java.awt.Color(102, 0, 0));
        lblAddingData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddingData1.setText("Adding Data");

        btnAddClient.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnAddClient.setForeground(new java.awt.Color(102, 0, 0));
        btnAddClient.setText("Add Client");
        btnAddClient.setDefaultCapable(false);
        btnAddClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddClientMouseClicked(evt);
            }
        });
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });

        btnAddHomePage.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnAddHomePage.setForeground(new java.awt.Color(0, 0, 102));
        btnAddHomePage.setText("Log Out");
        btnAddHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHomePageActionPerformed(evt);
            }
        });

        btnAddReservation.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnAddReservation.setForeground(new java.awt.Color(102, 0, 0));
        btnAddReservation.setText("Add Reservation");
        btnAddReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReservationActionPerformed(evt);
            }
        });

        btnAddPayment.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnAddPayment.setForeground(new java.awt.Color(102, 0, 0));
        btnAddPayment.setText("Add Payment");
        btnAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPaymentActionPerformed(evt);
            }
        });

        btnAddEmployee.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(102, 0, 0));
        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        txtClientID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientID.setForeground(new java.awt.Color(0, 0, 102));
        txtClientID.setText("ID");
        txtClientID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientIDMouseClicked(evt);
            }
        });

        txtClientName.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientName.setForeground(new java.awt.Color(0, 0, 102));
        txtClientName.setText("Name");
        txtClientName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientNameMouseClicked(evt);
            }
        });
        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });

        txtClientAddress.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientAddress.setForeground(new java.awt.Color(0, 0, 102));
        txtClientAddress.setText("City");
        txtClientAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientAddressMouseClicked(evt);
            }
        });

        txtClientFaculty.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientFaculty.setForeground(new java.awt.Color(0, 0, 102));
        txtClientFaculty.setText("Faculty");
        txtClientFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientFacultyMouseClicked(evt);
            }
        });

        txtClientEDate.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientEDate.setForeground(new java.awt.Color(0, 0, 102));
        txtClientEDate.setText("Eating Date");
        txtClientEDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientEDateMouseClicked(evt);
            }
        });

        txtClientPID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientPID.setForeground(new java.awt.Color(0, 0, 102));
        txtClientPID.setText("Payment ID");
        txtClientPID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientPIDMouseClicked(evt);
            }
        });

        txtClientRID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientRID.setForeground(new java.awt.Color(0, 0, 102));
        txtClientRID.setText("Reservation ID");
        txtClientRID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientRIDMouseClicked(evt);
            }
        });

        txtClientCID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientCID.setForeground(new java.awt.Color(0, 0, 102));
        txtClientCID.setText("Company ID");
        txtClientCID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientCIDMouseClicked(evt);
            }
        });

        txtMealType.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtMealType.setForeground(new java.awt.Color(0, 0, 102));
        txtMealType.setText("Meal Type");
        txtMealType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMealTypeMouseClicked(evt);
            }
        });

        txtMealPrice.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtMealPrice.setForeground(new java.awt.Color(0, 0, 102));
        txtMealPrice.setText("Price");
        txtMealPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMealPriceMouseClicked(evt);
            }
        });
        txtMealPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMealPriceActionPerformed(evt);
            }
        });

        txtMealCID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtMealCID.setForeground(new java.awt.Color(0, 0, 102));
        txtMealCID.setText("Company ID");
        txtMealCID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMealCIDMouseClicked(evt);
            }
        });

        txtEmployeeID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtEmployeeID.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeID.setText("ID");
        txtEmployeeID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmployeeIDMouseClicked(evt);
            }
        });

        txtEmployeeName.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtEmployeeName.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeName.setText("Name");
        txtEmployeeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmployeeNameMouseClicked(evt);
            }
        });
        txtEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeNameActionPerformed(evt);
            }
        });

        txtEmployeeAddress.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtEmployeeAddress.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeAddress.setText("City");
        txtEmployeeAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmployeeAddressMouseClicked(evt);
            }
        });

        txtEmployeeStartDate.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtEmployeeStartDate.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeStartDate.setText("Starting Date");
        txtEmployeeStartDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmployeeStartDateMouseClicked(evt);
            }
        });

        txtEmployeeCID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtEmployeeCID.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeCID.setText("Company ID");
        txtEmployeeCID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmployeeCIDMouseClicked(evt);
            }
        });

        txtPaymentDate.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtPaymentDate.setForeground(new java.awt.Color(0, 0, 102));
        txtPaymentDate.setText("Payment Date");
        txtPaymentDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPaymentDateMouseClicked(evt);
            }
        });

        txtPaymentMethod.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtPaymentMethod.setForeground(new java.awt.Color(0, 0, 102));
        txtPaymentMethod.setText("Payment Method");
        txtPaymentMethod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPaymentMethodMouseClicked(evt);
            }
        });
        txtPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentMethodActionPerformed(evt);
            }
        });

        txtPaymentID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtPaymentID.setForeground(new java.awt.Color(0, 0, 102));
        txtPaymentID.setText("ID");
        txtPaymentID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPaymentIDMouseClicked(evt);
            }
        });

        txtPaymentMealType.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtPaymentMealType.setForeground(new java.awt.Color(0, 0, 102));
        txtPaymentMealType.setText("Meal Type");
        txtPaymentMealType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPaymentMealTypeMouseClicked(evt);
            }
        });

        txtReservationDate.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtReservationDate.setForeground(new java.awt.Color(0, 0, 102));
        txtReservationDate.setText("Reservation Date");
        txtReservationDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReservationDateMouseClicked(evt);
            }
        });

        txtReservationMethod.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtReservationMethod.setForeground(new java.awt.Color(0, 0, 102));
        txtReservationMethod.setText("Reservation Method");
        txtReservationMethod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReservationMethodMouseClicked(evt);
            }
        });
        txtReservationMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationMethodActionPerformed(evt);
            }
        });

        txtReservationID.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtReservationID.setForeground(new java.awt.Color(0, 0, 102));
        txtReservationID.setText("ID");
        txtReservationID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReservationIDMouseClicked(evt);
            }
        });

        txtReservationMealType.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtReservationMealType.setForeground(new java.awt.Color(0, 0, 102));
        txtReservationMealType.setText("Meal Type");
        txtReservationMealType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReservationMealTypeMouseClicked(evt);
            }
        });

        btnAddMeal.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnAddMeal.setForeground(new java.awt.Color(102, 0, 0));
        btnAddMeal.setText("Add Meal");
        btnAddMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMealActionPerformed(evt);
            }
        });

        btnAddUpdate.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnAddUpdate.setForeground(new java.awt.Color(0, 0, 102));
        btnAddUpdate.setText("Update Data");
        btnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUpdateActionPerformed(evt);
            }
        });

        btnAddTable.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnAddTable.setForeground(new java.awt.Color(0, 0, 102));
        btnAddTable.setText("Tables");
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });

        btnAddDelete.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnAddDelete.setForeground(new java.awt.Color(0, 0, 102));
        btnAddDelete.setText("Delete Data");
        btnAddDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDeleteActionPerformed(evt);
            }
        });

        cmbEmployeeGender.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        cmbEmployeeGender.setForeground(new java.awt.Color(0, 0, 102));
        cmbEmployeeGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cmbEmployeeGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeGenderActionPerformed(evt);
            }
        });

        cmbClientGender.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        cmbClientGender.setForeground(new java.awt.Color(0, 0, 102));
        cmbClientGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cmbClientGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientGenderActionPerformed(evt);
            }
        });

        cmbClientType.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        cmbClientType.setForeground(new java.awt.Color(0, 0, 102));
        cmbClientType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "student", "staff" }));
        cmbClientType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(9, 9, 9)
                                                                .addComponent(txtEmployeeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cmbEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtEmployeeCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtMealPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(txtMealCID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtReservationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtReservationMethod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtReservationID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txtPaymentMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(txtReservationMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnAddPayment)
                                                        .addComponent(btnAddReservation)
                                                        .addComponent(btnAddEmployee)
                                                        .addComponent(btnAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnAddMeal))
                                                .addGap(26, 26, 26))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(txtClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(cmbClientGender, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtClientFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(cmbClientType, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(400, 400, 400))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtClientEDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtClientPID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtClientRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtClientCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(267, 267, 267)
                                                                .addComponent(lblAddingData1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(127, 127, 127)
                                                                .addComponent(btnAddHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnAddDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnAddTable, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(54, 154, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblAddingData1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtClientFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cmbClientGender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cmbClientType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtClientCID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtClientRID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtClientPID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtClientEDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtMealPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtMealCID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cmbEmployeeGender)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtEmployeeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtEmployeeCID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtPaymentMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtReservationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtReservationMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtReservationID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtReservationMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAddClient)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAddMeal)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAddEmployee)
                                                .addGap(19, 19, 19)
                                                .addComponent(btnAddPayment)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAddReservation)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddTable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127))
        );

        pack();
    }// </editor-fold>

    private void btnAddClientMouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {

        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String addInstruction = "insert into client (client_id, client_name,"
                    + "client_address, client_gender, client_fac, client_type, "
                    + "Edate, pid, rid, cid)"
                    + " values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
            statement = connection.prepareStatement(addInstruction);
            statement.setInt(1, Integer.valueOf(txtClientID.getText()));
            statement.setString(2, txtClientName.getText());
            statement.setString(3, txtClientAddress.getText());
            statement.setString(4, cmbClientGender.getSelectedItem().toString());
            statement.setString(5, txtClientFaculty.getText());
            statement.setString(6, cmbClientType.getSelectedItem().toString());
            statement.setString(7, txtClientEDate.getText());
            statement.setInt(8, Integer.valueOf(txtClientPID.getText()));
            statement.setInt(9, Integer.valueOf(txtClientRID.getText()));
            statement.setInt(10, Integer.valueOf(txtClientCID.getText()));

            int result = statement.executeUpdate();
            System.out.print(result);

            JOptionPane.showMessageDialog(this, "Added Client Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }

    }



    private void btnAddReservationActionPerformed(java.awt.event.ActionEvent evt) {

        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String addInstruction = "insert into reservatesfor (Rdate, res_meth,"
                    + "rid, meal_type)"
                    + " values (?, ?, ?, ?);";

            statement = connection.prepareStatement(addInstruction);
            statement.setString(1, txtReservationDate.getText());
            statement.setString(2, txtReservationMethod.getText());
            statement.setInt(3, Integer.valueOf(txtReservationID.getText()));
            statement.setString(4, txtReservationMealType.getText());

            int result = statement.executeUpdate();
            System.out.print(result);

            JOptionPane.showMessageDialog(this, "Added Reservation Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }

    private void btnAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {

        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String addInstruction = "insert into paysfor (Pdate, pay_meth,"
                    + "pid, meal_type)"
                    + " values (?, ?, ?, ?);";

            statement = connection.prepareStatement(addInstruction);
            statement.setString(1, txtPaymentDate.getText());
            statement.setString(2, txtPaymentMethod.getText());
            statement.setInt(3, Integer.valueOf(txtPaymentID.getText()));
            statement.setString(4, txtPaymentMealType.getText());

            int result = statement.executeUpdate();
            System.out.print(result);
            JOptionPane.showMessageDialog(this, "Added Payment Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {

        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String addInstruction = "insert into employee (Eid, Ename,"
                    + "Eaddress, Egender, Sdate, cid)"
                    + " values (?, ?, ?, ?, ?, ?);";

            statement = connection.prepareStatement(addInstruction);
            statement.setInt(1, Integer.valueOf(txtEmployeeID.getText()));
            statement.setString(2, txtEmployeeName.getText());
            statement.setString(3, txtEmployeeAddress.getText());
            statement.setString(4, cmbEmployeeGender.getSelectedItem().toString());
            statement.setString(5, txtEmployeeStartDate.getText());
            statement.setInt(6, Integer.valueOf(txtEmployeeCID.getText()));

            int result = statement.executeUpdate();
            System.out.print(result);
            JOptionPane.showMessageDialog(this, "Added Employee Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }

    private void txtClientIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientID.setText("");
    }

    private void txtClientNameMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientName.setText("");
    }

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtClientAddressMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientAddress.setText("");
    }

    private void txtClientFacultyMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientFaculty.setText("");
    }

    private void txtClientEDateMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientEDate.setText("");
    }

    private void txtClientPIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientPID.setText("");
    }

    private void txtClientRIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientRID.setText("");
    }

    private void txtClientCIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientCID.setText("");
    }

    private void txtMealTypeMouseClicked(java.awt.event.MouseEvent evt) {
        txtMealType.setText("");
    }

    private void txtMealPriceMouseClicked(java.awt.event.MouseEvent evt) {
        txtMealPrice.setText("");
    }

    private void txtMealPriceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtMealCIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtMealCID.setText("");
    }

    private void txtEmployeeIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtEmployeeID.setText("");
    }

    private void txtEmployeeNameMouseClicked(java.awt.event.MouseEvent evt) {
        txtEmployeeName.setText("");
    }

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtEmployeeAddressMouseClicked(java.awt.event.MouseEvent evt) {
        txtEmployeeAddress.setText("");
    }

    private void txtEmployeeStartDateMouseClicked(java.awt.event.MouseEvent evt) {
        txtEmployeeStartDate.setText("");
    }

    private void txtEmployeeCIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtEmployeeCID.setText("");
    }

    private void txtPaymentDateMouseClicked(java.awt.event.MouseEvent evt) {
        txtPaymentDate.setText("");
    }

    private void txtPaymentMethodMouseClicked(java.awt.event.MouseEvent evt) {
        txtPaymentMethod.setText("");
    }

    private void txtPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPaymentIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtPaymentID.setText("");
    }

    private void txtPaymentMealTypeMouseClicked(java.awt.event.MouseEvent evt) {
        txtPaymentMealType.setText("");
    }

    private void txtReservationDateMouseClicked(java.awt.event.MouseEvent evt) {
        txtReservationDate.setText("");
    }

    private void txtReservationMethodMouseClicked(java.awt.event.MouseEvent evt) {
        txtReservationMethod.setText("");
    }

    private void txtReservationMethodActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtReservationIDMouseClicked(java.awt.event.MouseEvent evt) {
        txtReservationID.setText("");
    }

    private void txtReservationMealTypeMouseClicked(java.awt.event.MouseEvent evt) {
        txtReservationMealType.setText("");
    }

    private void btnAddMealActionPerformed(java.awt.event.ActionEvent evt) {
        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String addInstruction = "insert into meal (meal_type, price,"
                    + "cid)"
                    + " values (?, ?, ?);";

            statement = connection.prepareStatement(addInstruction);
            statement.setString(1, txtMealType.getText());
            statement.setInt(2, Integer.valueOf(txtMealPrice.getText()));
            statement.setInt(3, Integer.valueOf(txtMealCID.getText()));

            int result = statement.executeUpdate();
            System.out.print(result);

            JOptionPane.showMessageDialog(this, "Added Meal Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }

    private void btnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        new frmUpdate().show();
        this.hide();
    }

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {
        new frmTable().show();
        this.hide();
    }

    private void btnAddDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        new frmDelete().show();
        this.hide();
    }

    private void btnAddHomePageActionPerformed(java.awt.event.ActionEvent evt) {

        new frmIntro().show();
        this.hide();
    }

    private void cmbEmployeeGenderActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void cmbClientGenderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cmbClientTypeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnAddDelete;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnAddHomePage;
    private javax.swing.JButton btnAddMeal;
    private javax.swing.JButton btnAddPayment;
    private javax.swing.JButton btnAddReservation;
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnAddUpdate;
    private javax.swing.JComboBox<String> cmbClientGender;
    private javax.swing.JComboBox<String> cmbClientType;
    private javax.swing.JComboBox<String> cmbEmployeeGender;
    private javax.swing.JLabel lblAddingData1;
    private javax.swing.JTextField txtClientAddress;
    private javax.swing.JTextField txtClientCID;
    private javax.swing.JTextField txtClientEDate;
    private javax.swing.JTextField txtClientFaculty;
    private javax.swing.JTextField txtClientID;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtClientPID;
    private javax.swing.JTextField txtClientRID;
    private javax.swing.JTextField txtEmployeeAddress;
    private javax.swing.JTextField txtEmployeeCID;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeeStartDate;
    private javax.swing.JTextField txtMealCID;
    private javax.swing.JTextField txtMealPrice;
    private javax.swing.JTextField txtMealType;
    private javax.swing.JTextField txtPaymentDate;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextField txtPaymentMealType;
    private javax.swing.JTextField txtPaymentMethod;
    private javax.swing.JTextField txtReservationDate;
    private javax.swing.JTextField txtReservationID;
    private javax.swing.JTextField txtReservationMealType;
    private javax.swing.JTextField txtReservationMethod;
    // End of variables declaration
}
