//@author Yağmur Doğan

import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmDelete extends javax.swing.JFrame {

    DefaultTableModel model;
    Connection connection = null;
    DbHelper dbHelper = new DbHelper();
    Statement statement = null;
    ResultSet resultSet;
    ArrayList<Client> clients = null;

    public frmDelete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnDeleteClient = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        txtEmployeeIDDelete = new javax.swing.JTextField();
        lblDeletingData1 = new javax.swing.JLabel();
        txtClientIDDelete = new javax.swing.JTextField();
        btnDeleteUpdate = new javax.swing.JButton();
        btnDeleteTable = new javax.swing.JButton();
        btnDeleteAdd = new javax.swing.JButton();
        btnDeleteHomePage = new javax.swing.JButton();
        btnDeleteMeal = new javax.swing.JButton();
        txtMealTypeDelete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDeleteClient.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnDeleteClient.setForeground(new java.awt.Color(102, 0, 0));
        btnDeleteClient.setText("Delete Client");
        btnDeleteClient.setDefaultCapable(false);
        btnDeleteClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteClientMouseClicked(evt);
            }
        });
        btnDeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClientActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnDeleteEmployee.setForeground(new java.awt.Color(102, 0, 0));
        btnDeleteEmployee.setText("Delete Employee");
        btnDeleteEmployee.setDefaultCapable(false);
        btnDeleteEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteEmployeeMouseClicked(evt);
            }
        });
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        txtEmployeeIDDelete.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtEmployeeIDDelete.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeIDDelete.setText("ID");
        txtEmployeeIDDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmployeeIDDeleteMouseClicked(evt);
            }
        });

        lblDeletingData1.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        lblDeletingData1.setForeground(new java.awt.Color(102, 0, 0));
        lblDeletingData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeletingData1.setText("Deleting Data");

        txtClientIDDelete.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtClientIDDelete.setForeground(new java.awt.Color(0, 0, 102));
        txtClientIDDelete.setText("ID");
        txtClientIDDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClientIDDeleteMouseClicked(evt);
            }
        });

        btnDeleteUpdate.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnDeleteUpdate.setForeground(new java.awt.Color(0, 0, 102));
        btnDeleteUpdate.setText("Update Data");
        btnDeleteUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUpdateActionPerformed(evt);
            }
        });

        btnDeleteTable.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnDeleteTable.setForeground(new java.awt.Color(0, 0, 102));
        btnDeleteTable.setText("Tables");
        btnDeleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTableActionPerformed(evt);
            }
        });

        btnDeleteAdd.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnDeleteAdd.setForeground(new java.awt.Color(0, 0, 102));
        btnDeleteAdd.setText("Add Data");
        btnDeleteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAddActionPerformed(evt);
            }
        });

        btnDeleteHomePage.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnDeleteHomePage.setForeground(new java.awt.Color(0, 0, 102));
        btnDeleteHomePage.setText("Log Out");
        btnDeleteHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHomePageActionPerformed(evt);
            }
        });

        btnDeleteMeal.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnDeleteMeal.setForeground(new java.awt.Color(102, 0, 0));
        btnDeleteMeal.setText("Delete Meal");
        btnDeleteMeal.setDefaultCapable(false);
        btnDeleteMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMealMouseClicked(evt);
            }
        });
        btnDeleteMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMealActionPerformed(evt);
            }
        });

        txtMealTypeDelete.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        txtMealTypeDelete.setForeground(new java.awt.Color(0, 0, 102));
        txtMealTypeDelete.setText("Meal Type");
        txtMealTypeDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMealTypeDeleteMouseClicked(evt);
            }
        });
        txtMealTypeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMealTypeDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(152, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtClientIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(64, 64, 64)
                                                                .addComponent(btnDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtEmployeeIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtMealTypeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(21, 21, 21)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnDeleteMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(321, 321, 321))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnDeleteHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDeleteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDeleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnDeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(101, 101, 101))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblDeletingData1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(239, 239, 239))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblDeletingData1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClientIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteClient))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEmployeeIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteEmployee))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMealTypeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteMeal))
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnDeleteClientMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btnDeleteClientActionPerformed(java.awt.event.ActionEvent evt) {
        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String deleteInstruction = "delete from client where client_id = ?";

            statement = connection.prepareStatement(deleteInstruction);
            statement.setInt(1, Integer.valueOf(txtClientIDDelete.getText()));

            int result = statement.executeUpdate();
            System.out.print(result);

            JOptionPane.showMessageDialog(this, "Deleted Client Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }

    private void btnDeleteEmployeeMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {
        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String deleteInstruction = "delete from employee where Eid = ?";

            statement = connection.prepareStatement(deleteInstruction);
            statement.setInt(1, Integer.valueOf(txtEmployeeIDDelete.getText()));

            int result = statement.executeUpdate();
            System.out.print(result);

            JOptionPane.showMessageDialog(this, "Deleted Employee Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }

    private void txtEmployeeIDDeleteMouseClicked(java.awt.event.MouseEvent evt) {
        txtEmployeeIDDelete.setText("");
    }

    private void txtClientIDDeleteMouseClicked(java.awt.event.MouseEvent evt) {
        txtClientIDDelete.setText("");
    }

    private void btnDeleteUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        new frmUpdate().show();
        this.hide();
    }

    private void btnDeleteTableActionPerformed(java.awt.event.ActionEvent evt) {
        new frmTable().show();
        this.hide();
    }

    private void btnDeleteAddActionPerformed(java.awt.event.ActionEvent evt) {
        new frmAdd().show();
        this.hide();
    }

    private void btnDeleteHomePageActionPerformed(java.awt.event.ActionEvent evt) {

        new frmIntro().show();
        this.hide();
    }

    private void btnDeleteMealMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btnDeleteMealActionPerformed(java.awt.event.ActionEvent evt) {
        PreparedStatement statement = null;

        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 0;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        try{

            String deleteInstruction = "delete from meal where meal_type = ?";

            statement = connection.prepareStatement(deleteInstruction);
            statement.setString(1, txtMealTypeDelete.getText());

            int result = statement.executeUpdate();
            System.out.print(result);

            JOptionPane.showMessageDialog(this, "Deleted Meal Data!");

        }catch(SQLException exception){
            dbHelper.showError(exception);
        }
        try {
            connection = dbHelper.getConnection();
            String setForeignKeyCheck = "SET foreign_key_checks = 1;";
            statement = connection.prepareStatement(setForeignKeyCheck);
        } catch (SQLException e) {

        }
        finally{

            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }

    private void txtMealTypeDeleteMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void txtMealTypeDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        txtMealTypeDelete.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnDeleteAdd;
    private javax.swing.JButton btnDeleteClient;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnDeleteHomePage;
    private javax.swing.JButton btnDeleteMeal;
    private javax.swing.JButton btnDeleteTable;
    private javax.swing.JButton btnDeleteUpdate;
    private javax.swing.JLabel lblDeletingData1;
    private javax.swing.JTextField txtClientIDDelete;
    private javax.swing.JTextField txtEmployeeIDDelete;
    private javax.swing.JTextField txtMealTypeDelete;
    // End of variables declaration
}
