//@author Yağmur Doğan

public class frmLoginESY extends javax.swing.JFrame {

    /**
     * Creates new form frmLoginESY
     */
    public frmLoginESY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnDeleteESY = new javax.swing.JButton();
        btnAddDataESY = new javax.swing.JButton();
        lblYEY = new javax.swing.JLabel();
        btnLoginPageESY = new javax.swing.JButton();
        btnUpdateESY = new javax.swing.JButton();
        btnTableESY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDeleteESY.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnDeleteESY.setForeground(new java.awt.Color(0, 0, 102));
        btnDeleteESY.setText("Delete Data");
        btnDeleteESY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteESYActionPerformed(evt);
            }
        });

        btnAddDataESY.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnAddDataESY.setForeground(new java.awt.Color(0, 0, 102));
        btnAddDataESY.setText("Add Data");
        btnAddDataESY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataESYActionPerformed(evt);
            }
        });

        lblYEY.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        lblYEY.setForeground(new java.awt.Color(102, 0, 0));
        lblYEY.setText("In this page you can choose which process you intend to run.");

        btnLoginPageESY.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnLoginPageESY.setForeground(new java.awt.Color(0, 0, 102));
        btnLoginPageESY.setText("Log Out");
        btnLoginPageESY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPageESYActionPerformed(evt);
            }
        });

        btnUpdateESY.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnUpdateESY.setForeground(new java.awt.Color(0, 0, 102));
        btnUpdateESY.setText("Update Data");
        btnUpdateESY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateESYActionPerformed(evt);
            }
        });

        btnTableESY.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnTableESY.setForeground(new java.awt.Color(0, 0, 102));
        btnTableESY.setText("Tables");
        btnTableESY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableESYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAddDataESY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLoginPageESY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateESY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDeleteESY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTableESY, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(309, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblYEY, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblYEY, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnLoginPageESY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddDataESY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateESY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteESY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTableESY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnDeleteESYActionPerformed(java.awt.event.ActionEvent evt) {
        new frmDelete().show();
        this.hide();
    }

    private void btnAddDataESYActionPerformed(java.awt.event.ActionEvent evt) {
        new frmAdd().show();
        this.hide();
    }

    private void btnLoginPageESYActionPerformed(java.awt.event.ActionEvent evt) {

        new frmIntro().show();
        this.hide();
    }

    private void btnUpdateESYActionPerformed(java.awt.event.ActionEvent evt) {
        new frmUpdate().show();
        this.hide();
    }

    private void btnTableESYActionPerformed(java.awt.event.ActionEvent evt) {
        new frmTable().show();
        this.hide();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoginESY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoginESY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoginESY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoginESY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoginESY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddDataESY;
    private javax.swing.JButton btnDeleteESY;
    private javax.swing.JButton btnLoginPageESY;
    private javax.swing.JButton btnTableESY;
    private javax.swing.JButton btnUpdateESY;
    private javax.swing.JLabel lblYEY;
    // End of variables declaration
}
